version: 2.1
executors:
  main:
    docker:
      - image: asobiek/cimg-openjdk-rust:jdk-17.0.2-rust-1.59
    working_directory: ~/orion
    environment:
      JVM_OPTS: -Xmx7168m
      TERM: dumb
    resource_class: large
jobs:
  test:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/build.gradle.kts" }}
            - v1-cargo-cache-{{ arch }}-{{ checkcum "lib/anvil/Cargo.lock" }}
      - run:
          name: "Testing"
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "server/build.gradle.kts" }}
      - save_cache:
          paths:
            - lib/anvil/target/release/.fingerprint
            - lib/anvil/target/release/build
            - lib/anvil/target/release/deps
          key: v1-cargo-cache-{{ arch }}-{{ checkcum "lib/anvil/Cargo.lock" }}
  build:
    executor: main
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/build.gradle.kts" }}
            - v1-cargo-cache-{{ arch }}-{{ checkcum "lib/anvil/Cargo.lock" }}
      - run:
          name: "Setup Environment"
          command: mkdir -p /tmp/artifacts && echo "export ORION_VERSION=$(gradle --quiet :orion-server:version)" >> $BASH_ENV
      # - run: gradle test
      - run: |
          gradle :orion-api:build
          cp api/build/libs/orion-api-$ORION_VERSION-shaded.jar /tmp/artifacts/orion-api-$ORION_VERSION-${CIRCLE_BUILD_NUM:="UNKNOWN"}.jar
      - run: |
          gradle :orion-server:build
          cp server/build/libs/orion-server-$ORION_VERSION-shaded.jar /tmp/artifacts/orion-server-$ORION_VERSION-${CIRCLE_BUILD_NUM:="UNKNOWN"}.jar
      - store_artifacts:
          path: /tmp/artifacts
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "settings.gradle.kts" }}
      - save_cache:
          paths:
            - lib/anvil/target/release/.fingerprint
            - lib/anvil/target/release/build
            - lib/anvil/target/release/deps
          key: v1-cargo-cache-{{ arch }}-{{ checkcum "lib/anvil/Cargo.lock" }}
workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main